### ISSUE TITLE
app getting crashed when back button pressed and gives kotlin null pointer exception 

### ISSUE THREAD

**Issue by rohitk1011** [Almoullim/background_location#134]
PlatformException(error, null, null, kotlin.KotlinNullPointerException I/flutter ( 2330):  at com.almoullim.background_location.BackgroundLocationService.startLocationService(BackgroundLocationService.kt:105)

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {../..../MainActivity}: h.a
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by h.a
       at com.almoullim.background_location.BackgroundLocationService.stopLocationService(BackgroundLocationService.java)
       at com.almoullim.background_location.BackgroundLocationService.setActivity(BackgroundLocationService.java)
       at com.almoullim.background_location.BackgroundLocationPlugin.onDetachedFromActivity(BackgroundLocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java)
       at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java)
       at android.app.Activity.performDestroy(Activity.java:7223)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
       at android.app.ActivityThread.-wrap7(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by eduardo-and** [comment]
Same problem here!

**Comment by MoralCode** [comment]
Is this still an issue?

**Comment by MoralCode** [comment]
It appears commits were made to raise the notification importance around the time this was closed.

If you can show a stack trace that both a) _matches the one in the initial issue description_ and happens _while running the lastest code from the main branch (v0.13.0 or later)_ then this issue will be reopened

**Comment by urvashiN1608** [comment]
can you please provide solution asap

**Comment by MoralCode** [comment]
Solution has already been provided
