### ISSUE TITLE
Android memory leak when terminating the app with active foreground service

### ISSUE THREAD

**Issue by tomk9** [Almoullim/background_location#7]
```
2019-09-19 17:56:59.699 1728-1965/? W/SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{a171bab token=Token{68e89fa ActivityRecord{d069425 u0 com.example.backgeound_location_example/.MainActivity t138}}}#0
2019-09-19 17:56:59.702 8072-8072/com.example.backgeound_location_example E/ActivityThread: Activity com.example.backgeound_location_example.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@7049b1 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.example.backgeound_location_example.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@7049b1 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1610)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1502)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1659)
        at android.app.ContextImpl.bindService(ContextImpl.java:1612)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
        at com.almoullim.background_location.BackgroundLocationPlugin.onMethodCall(BackgroundLocationPlugin.kt:83)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-09-19 17:56:59.706 1891-2430/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@2143468
```

**Comment by afung2468** [comment]
Does anyone have a work-around for this?

**Comment by mohan-dev1248** [comment]
Any update on this?

**Comment by mohan-dev1248** [comment]
I went through the code. You are doing a onBind method when starting the service. If you can do the unBind() method when we are  closing the App. I am not really sure how to do that.

**Comment by 2math** [comment]
I can see that on exit app the location plugin is unbounding on it's side, maybe the example can be taken from there
https://github.com/Lyokone/flutterlocation
